---
- name: Copy cluster.conf
  template: src=cluster.conf dest={{install_dir}}/nacos/conf mode=644 owner={{ user }} group = {{ group }}

- name: Copy application.properties
  template: src=application-{{ nacos_version }}.properties dest={{install_dir}}/nacos/conf/application.properties mode=755 owner={{ user }} group = {{ group }}

- name: install openjdk-devel
  yum: name=java-1.8.0-openjdk-devel  state=present

- name: install systemd service
  template: src=nacos.service.j2 dest=/usr/lib/systemd/system/nacos.service

- name: reload service
  shell: systemctl daemon-reload

- name: enable service
  service:
    name: nacos
    enabled: yes

- name: start service
  service:
    name: nacos
    state: started
